// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "node prisma/seed.js", // <-- Baris ini ditambahkan untuk konfigurasi seed
  },
  datasource: {
    // Use DIRECT_URL (Session Pooler port 5432) for Prisma CLI — avoids P1017 on Transaction Pooler (port 6543)
    url: process.env["DIRECT_URL"] ?? process.env["DATABASE_URL"],
  },
});